"use client";

import React, { useState } from "react";
import { Copy, Check, Download } from "lucide-react";

export default function RobotsGenerator() {
  const [userAgent, setUserAgent] = useState("*");
  const [allow, setAllow] = useState("/");
  const [disallow, setDisallow] = useState("/admin/\n/api/\n/checkout/");
  const [sitemap, setSitemap] = useState("https://example.com/sitemap.xml");
  const [copied, setCopied] = useState(false);

  const disallowRules = disallow
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => `Disallow: ${line}`)
    .join("\n");

  const robotsTxt = `# robots.txt generated by FastSEOKit
User-agent: ${userAgent}
Allow: ${allow}
${disallowRules ? disallowRules + "\n" : ""}
Sitemap: ${sitemap}`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(robotsTxt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([robotsTxt], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-6">
      <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm space-y-4">
        <h2 className="text-lg font-bold text-gray-900">Robots Configuration</h2>
        
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1">User-Agent</label>
          <input
            type="text"
            value={userAgent}
            onChange={(e) => setUserAgent(e.target.value)}
            className="w-full px-3 py-2 border rounded-lg text-sm text-gray-900"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1">Allowed Path</label>
          <input
            type="text"
            value={allow}
            onChange={(e) => setAllow(e.target.value)}
            className="w-full px-3 py-2 border rounded-lg text-sm text-gray-900"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1">Disallowed Paths (one per line)</label>
          <textarea
            rows={4}
            value={disallow}
            onChange={(e) => setDisallow(e.target.value)}
            className="w-full px-3 py-2 border rounded-lg text-sm text-gray-900 font-mono"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1">Sitemap URL</label>
          <input
            type="text"
            value={sitemap}
            onChange={(e) => setSitemap(e.target.value)}
            className="w-full px-3 py-2 border rounded-lg text-sm text-gray-900"
          />
        </div>
      </div>

      <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between">
        <div>
          <h2 className="text-lg font-bold text-gray-900 mb-4">Preview (robots.txt)</h2>
          <pre className="p-4 bg-gray-900 text-emerald-400 font-mono text-xs rounded-lg overflow-x-auto whitespace-pre-wrap">
            {robotsTxt}
          </pre>
        </div>

        <div className="flex gap-3 mt-6">
          <button
            onClick={handleCopy}
            className="flex-1 py-2 px-4 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? "Copied" : "Copy Output"}
          </button>
          <button
            onClick={handleDownload}
            className="flex-1 py-2 px-4 bg-gray-900 hover:bg-gray-800 text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2"
          >
            <Download size={16} /> Download
          </button>
        </div>
      </div>
    </div>
  );
}
