"use client";

import React, { useState } from "react";
import { Copy, Check, Download, Bot, Terminal } from "lucide-react";

export default function RobotsGenerator() {
  const [userAgent, setUserAgent] = useState("*");
  const [allow, setAllow] = useState("/");
  const [disallow, setDisallow] = useState("/admin/\n/api/\n/checkout/\n/private/");
  const [sitemap, setSitemap] = useState("https://example.com/sitemap.xml");
  const [copied, setCopied] = useState(false);

  const disallowRules = disallow
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => `Disallow: ${line}`)
    .join("\n");

  const robotsTxt = `# robots.txt generated by FastSEOKit
User-agent: ${userAgent}
Allow: ${allow}
${disallowRules ? disallowRules + "\n" : ""}
Sitemap: ${sitemap}`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(robotsTxt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([robotsTxt], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 w-full max-w-5xl mx-auto items-stretch">
      {/* Configuration Column */}
      <div className="bg-white p-6 sm:p-7 rounded-2xl border border-neutral-200/90 shadow-xs flex flex-col justify-between space-y-4">
        <div className="border-b border-neutral-100 pb-3 flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold text-neutral-900">Bot Crawl Rules</h2>
            <p className="text-xs text-neutral-500">Configure indexing rules for search engines</p>
          </div>
          <span className="p-2 bg-blue-50 text-blue-600 rounded-lg">
            <Bot size={18} />
          </span>
        </div>

        <div className="space-y-3.5 flex-1">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-bold text-neutral-700 mb-1.5 uppercase tracking-wider">User-Agent</label>
              <input
                type="text"
                value={userAgent}
                onChange={(e) => setUserAgent(e.target.value)}
                className="w-full h-11 px-3.5 border border-neutral-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-600 text-neutral-900 text-sm font-medium"
                placeholder="*"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-neutral-700 mb-1.5 uppercase tracking-wider">Allow Path</label>
              <input
                type="text"
                value={allow}
                onChange={(e) => setAllow(e.target.value)}
                className="w-full h-11 px-3.5 border border-neutral-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-600 text-neutral-900 text-sm font-medium"
                placeholder="/"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold text-neutral-700 mb-1.5 uppercase tracking-wider">Disallowed Directories (1 per line)</label>
            <textarea
              rows={4}
              value={disallow}
              onChange={(e) => setDisallow(e.target.value)}
              className="w-full p-3 border border-neutral-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-600 text-neutral-900 text-sm font-mono"
              placeholder="/admin/"
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-neutral-700 mb-1.5 uppercase tracking-wider">Sitemap XML URL</label>
            <input
              type="text"
              value={sitemap}
              onChange={(e) => setSitemap(e.target.value)}
              className="w-full h-11 px-3.5 border border-neutral-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-600 text-neutral-900 text-sm font-medium"
              placeholder="https://example.com/sitemap.xml"
            />
          </div>
        </div>

        <p className="text-[11px] text-neutral-400 pt-2 border-t border-neutral-100">
          Tip: Place the exported robots.txt file directly in your public root directory.
        </p>
      </div>

      {/* Code Preview Column */}
      <div className="bg-white p-6 sm:p-7 rounded-2xl border border-neutral-200/90 shadow-xs flex flex-col justify-between space-y-4">
        <div className="border-b border-neutral-100 pb-3 flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold text-neutral-900">Output Preview</h2>
            <p className="text-xs text-neutral-500">Live preview of your robots.txt file</p>
          </div>
          <span className="p-2 bg-neutral-100 text-neutral-700 rounded-lg font-mono text-xs font-bold">
            robots.txt
          </span>
        </div>

        <div className="flex-1 flex flex-col">
          <div className="flex-1 bg-neutral-950 p-4 rounded-xl border border-neutral-800 flex flex-col overflow-hidden shadow-inner">
            <div className="flex items-center gap-2 pb-2 mb-2 border-b border-neutral-800 text-[11px] text-neutral-400 font-mono">
              <span className="w-2.5 h-2.5 rounded-full bg-rose-500/80"></span>
              <span className="w-2.5 h-2.5 rounded-full bg-amber-500/80"></span>
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/80"></span>
              <span className="ml-2">utf-8 plaintext</span>
            </div>
            <pre className="font-mono text-xs sm:text-sm text-emerald-400 leading-relaxed overflow-x-auto whitespace-pre-wrap flex-1">
              {robotsTxt}
            </pre>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3 pt-2">
          <button
            onClick={handleCopy}
            className="h-11 px-4 bg-blue-600 hover:bg-blue-700 active:scale-95 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-2 transition-all shadow-md shadow-blue-600/20"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? "Copied!" : "Copy Output"}
          </button>
          <button
            onClick={handleDownload}
            className="h-11 px-4 bg-neutral-900 hover:bg-neutral-800 active:scale-95 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-2 transition-all"
          >
            <Download size={16} /> Download .txt
          </button>
        </div>
      </div>
    </div>
  );
}
